Missing bech32.h
gcc -c -o generate_npub.o generate_npub.c -I/usr/local/include -I/usr/include/openssl -g -Wall
generate_npub.c:13:10: fatal error: bech32.h: No such file or directory
   13 | #include "bech32.h"
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:15: generate_npub.o] Error 1
p